# Generated by Django 2.1.5 on 2019-01-11 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0002_client_dateofvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dateofvisit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
