# Generated by Django 2.1.5 on 2019-01-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0003_auto_20190111_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
