# Generated by Django 2.1.5 on 2019-01-11 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patiladmin', '0004_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('contact', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('pVisit', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.BigIntegerField()),
                ('dateofvisit', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
