# Generated by Django 2.1.5 on 2019-01-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0005_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
