# Generated by Django 2.1.5 on 2019-01-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0007_auto_20190111_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=255)),
                ('dtOfApmt', models.CharField(max_length=255)),
                ('tmOfApmt', models.CharField(max_length=255)),
            ],
        ),
    ]
