# Generated by Django 2.1.5 on 2019-01-13 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0008_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='schOn',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
