# Generated by Django 2.1.5 on 2019-01-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0009_appointments_schon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='schOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
