# Generated by Django 2.1.5 on 2019-01-13 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0010_auto_20190113_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='schOn',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
