# Generated by Django 2.1.5 on 2019-01-13 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0011_auto_20190113_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointments',
            options={'verbose_name_plural': 'Appointments'},
        ),
    ]
