# Generated by Django 2.1.5 on 2019-01-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0013_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hAbout',
            field=models.CharField(default='Through some reference', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='toMeet',
            field=models.CharField(default='Adv. Pranav Patil', max_length=255),
            preserve_default=False,
        ),
    ]
