# Generated by Django 2.1.5 on 2019-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patiladmin', '0014_auto_20190118_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='caseSynopsis',
            field=models.TextField(default='No case data provided by client'),
        ),
    ]
